version: '3.5'

services:

  i2b2-etl:
    image: i2b2-etl:latest
    build: ./
    container_name: i2b2-etl
    environment:
      - PROJECT=${PROJECT}
      - UPDATE_DATE=${UPDATE_DATE}
      - PROJECT_TEXT= ${PROJECT_TEXT}
      - ACCOUNT=${ACCOUNT}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - WAREHOUSE=${WAREHOUSE}
      - ROLE=${ROLE}
      - JDBC_URL=${JDBC_URL}
      - TARGET_DB=${TARGET_DB}
      - TARGET_SCHEMA=${TARGET_SCHEMA}
      - SOURCE_DB=${SOURCE_DB}
      - SOURCE_SCHEMA=${SOURCE_SCHEMA}
      - PM_DB=${PM_DB}

    networks:
      - i2b2-etl
      
networks:
  i2b2-etl:
    name: i2b2-etl
